# Generated by Django 6.0.4 on 2026-04-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birthday_coupon_sent', models.BooleanField(default=False)),
                ('birthday_coupon_year', models.IntegerField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('referral_credits', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subscription_plan', models.CharField(choices=[('none', 'No Plan'), ('basic', 'Basic - ₹99/month'), ('premium', 'Premium - ₹199/month')], default='none', max_length=20)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
