# Generated by Django 6.0.4 on 2026-04-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('discount_percent', models.PositiveIntegerField(default=20, help_text='Discount percentage (e.g. 20 for 20%)')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_color', models.CharField(default='#ff4444', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
